language: python
dist: bionic

jobs:
  include:
    - name: "Run Tests Python 3.6"
      python: 3.6
      env: TOX_ENV=py36
    - name: "Run Tests Python 3.7"
      python: 3.7
      env: TOX_ENV=py37
    - name: "Run Tests Python 3.8"
      python: 3.8
      env: TOX_ENV=py38
    - name: "Lint Flake8"
      python: 3.8
      env: TOX_ENV=lint
    - name: "isort-check"
      python: 3.8
      env: TOX_ENV=isort-check
    - name: "Travis Coveralls Reporting"
      python: 3.8
      env: TOX_ENV=travis-coveralls

install:
  - pip install -U pip setuptools tox

script: |
  tox -e $TOX_ENV
